/* Interface text for the interactive page, English. Same keys as ui.zh.js.
   Keys used in the page's HTML as {{key}} must be plain strings; the rest may be functions. */
const UI = {
  lang: 'en',
  caseTitle: 'Night Heron',
  pdfName: 'night-heron.pdf',
  description: 'A privacy mystery: find the whistleblower who gave themselves away through a photo’s metadata, its background and their writing habits.',
  // no-JS and fallback notices (HTML)
  nojsTitle: 'This version needs JavaScript',
  nojsBody: 'The interactive Night Heron simulates an investigator’s computer and needs JavaScript to run. Your browser has JavaScript turned off, for example at Tor Browser’s “Safest” security level.',
  nojsStatic: 'The static version needs no JavaScript and has the whole case:',
  nojsGo: 'Play the static version',
  nojsPdf: 'To play offline or on paper, <a href="night-heron.pdf" download="night-heron.pdf">download the PDF</a> (the solution is on the last pages).',
  fallbackTitle: 'The interactive version can’t run in this browser',
  fallbackLoad: 'Something went wrong while loading.',
  fallbackStay: 'Keep trying the interactive version',
  fallbackFeatures: 'Your browser is missing features the interactive version needs.',
  // desktop
  stickyTitle: 'Tonight’s job',
  sticky1: 'Read Night Heron’s messages',
  sticky2: 'Find what the photo gave away',
  sticky3: 'Narrow six people to one',
  sticky4: 'File the case report',
  station: 'Mistport Workstation',
  appChat: 'Secure chat',
  lobbyHref: '../',
  langHref: '../../night-heron/',
  otherLang: 'zh-Hant-TW',
  menuLobby: 'Case board',
  menuLobbyTitle: 'Back to all cases',
  menuPdf: 'PDF',
  menuPdfTitle: 'Printable PDF, solution on the last pages',
  menuLang: '中文',
  menuLangTitle: 'Chinese version',
  menuReset: 'Start over',
  menuResetConfirm: 'Tap again to start over',
  clockDate: 'Wed 16 Sep ',
  moreLabel: 'More',
  dockLabel: 'Apps',
  apps: { chat: 'Secure chat', browser: 'Browser', files: 'Files', viewer: 'Images', doc: 'Document', terminal: 'Terminal', board: 'Evidence', report: 'Case report' },
  locked: ' (locked)',
  close: 'Close',
  minimize: 'Minimise',
  lockedToast: ['Not yet', 'Finish talking to Night Heron and accept the files first.'],
  // toasts and pins
  clueToast: 'New clue saved to the evidence board',
  pin: '📌 Pin',
  pinned: 'Pinned',
  pinnedToast: 'Pinned to the evidence board',
  downloadToast: fn => ['Downloaded', fn + ' → Downloads'],
  // chat
  yelu: 'Night Heron',
  awu: 'Fog · Mistport Aid',
  yeluAvatar: 'NH',
  awuAvatar: 'F',
  e2e: 'End-to-end encrypted',
  typing: 'typing…',
  awuSub: 'Hints and support',
  headYelu: 'Night Heron · safety number verified',
  headYeluTyping: 'Night Heron is typing…',
  headAwu: 'Fog · Mistport Aid internal channel',
  chatOpening: '— Safety number verified · messages disappear after 24 hours —',
  zipName: 'heron-export.zip',
  zipMeta: '48 KB · sent encrypted',
  zipSent: 'Sent a file: heron-export.zip',
  zipReceived: 'Received heron-export.zip · unpacked to ~/heron-export',
  received: 'Received ✓',
  accept: 'Accept',
  typingAria: 'Night Heron is typing',
  caseOpen: '— Case accepted · investigation open —',
  startToast: ['Investigation open', 'All apps are unlocked. Start with the browser, files or terminal.'],
  awuHello: "I'm Fog, on duty tonight. You've taken the Night Heron case?",
  hintButton: (n, total) => `Give me a hint (${n}/${total} used)`,
  helperButton: on => `${on ? 'Turn off' : 'Turn on'} terminal beginner help`,
  hintAsk: 'Give me a hint.',
  hintLine: (n, total, h) => `Hint ${n}/${total}: ${h}`,
  hintsDone: "That's every hint. The rest is up to your instincts… no, up to the evidence.",
  openBrowser: 'Open the browser',
  openFiles: 'Open Night Heron’s export',
  fastForward: 'Skip ▸▸',
  chooseReply: 'Choose your reply',
  acceptHint: 'Tap “Accept” on the file to receive it',
  skipIntro: 'Skip the opening',
  // browser
  back: 'Back',
  forward: 'Forward',
  reload: 'Reload',
  address: 'Address',
  previewAttachment: 'Preview attachment',
  downloaded: 'Downloaded ✓',
  downloadOriginal: 'Download original',
  saveImage: 'Save image',
  uploaded: 'Uploaded',
  upload: 'Upload',
  trap: ['Wait. Did you just upload Night Heron’s original photo to some website?', "That site has the photo now, along with your IP address and the upload time. If the company's investigators find it too…\nNext time, check it with a tool on your own computer, like exiftool in the terminal. Your rank for this case drops a level."],
  // files and documents
  sideHome: 'Home',
  sideDownloads: 'Downloads',
  sideSlack: 'Slack logs',
  upOne: 'Up one level',
  checkInTerminal: 'Check in terminal',
  downloadsEmpty: 'Downloads is empty.<br>Files you download in the browser show up here.',
  folderEmpty: 'This folder is empty.',
  filesTitle: dir => 'Files — ' + dir,
  verbatim: 'Quoted as written; punctuation and spacing are untouched.',
  colon: ': ',
  // viewer
  viewerEmpty: 'No image open yet.<br>Tap an image in Downloads, or the forum attachment, to open it.',
  viewerTitle: fn => 'Images — ' + fn,
  zoomOut: 'Zoom out',
  zoomIn: 'Zoom in',
  fit: 'Fit',
  fileInfo: 'File info',
  infoFile: 'File',
  infoName: 'Name',
  infoSize: 'Dimensions',
  infoBytes: 'Size',
  infoWhere: 'Location',
  infoPreview: '(web preview, not downloaded)',
  cameraInfo: 'Camera',
  noCamera: 'This file has no camera information.',
  tipDownloaded: 'Only common fields are listed here; some are left out. An EXIF tool can read the full metadata.',
  tipNotDownloaded: 'To see camera details, <b>download</b> the original first.',
  saveFile: 'Save this file to your computer',
  realJpeg: 'It’s a real JPEG; check it with your own tools too.',
  controls: phone => 'Controls: ' + (phone ? 'pinch to zoom, drag to move, double-tap to zoom in.' : 'scroll or +/− to zoom, drag to move, double-click to zoom in.'),
  // terminal
  termInput: 'Terminal command',
  termWelcome: 'Type <span class="k">help</span> to see the commands.',
  tbCommand: 'Command',
  tbPattern: 'Text to find',
  tbPatternAria: 'Text for grep to find',
  tbAdd: 'Add',
  tbFolders: 'Folders',
  tbFiles: 'Files',
  tbBack: 'Remove the last part',
  tbHistory: '↑ Previous',
  tbKeyboard: '⌨ Type it myself',
  run: 'Run ↵',
  suggested: 'Suggested commands (tap to fill in)',
  useBuilder: 'Use command blocks',
  helperToggle: on => `Beginner help: ${on ? 'on' : 'off'}`,
  help: `Commands:
  <span class="k">ls</span> [folder]           list files
  <span class="k">cd</span> &lt;folder&gt;           change folder (cd .. goes up)
  <span class="k">pwd</span>                   show where you are
  <span class="k">cat</span> &lt;file&gt;             show a text file
  <span class="k">exiftool</span> &lt;file&gt;        read a file's metadata
  <span class="k">grep</span> [-i] &lt;text&gt; &lt;files...&gt;  search files for text; *.log works
  <span class="k">file</span> &lt;file&gt;            tell a file's type
  <span class="k">open</span> &lt;file&gt;            open it in its app
  <span class="k">clear</span>                 clear the screen
<span class="d">Tip: Tab completes file names; ↑ ↓ bring back earlier commands.</span>`,
  noSuchFileOrDir: 'No such file or directory',
  empty: '(empty)',
  noSuchDir: 'No such directory',
  isDir: 'Is a directory',
  noSuchFile: 'No such file',
  cannotOpen: 'cannot open',
  binary: '(binary file, unreadable gibberish… try exiftool or open)',
  usage: 'usage',
  usageCat: 'usage: cat &lt;file&gt;',
  usageOpen: 'usage: open &lt;file&gt;',
  usageExif: 'usage: exiftool &lt;file&gt;</span>\n<span class="d">e.g. exiftool PXL_20260914_144712345.jpg',
  usageGrep: 'usage: grep [-i] &lt;text&gt; &lt;files...&gt;</span>\n<span class="d">e.g. grep Pixel slack/*.log',
  noMatch: '(no matches)',
  disabledCmd: 'This workstation has that command disabled. Focus on the case.',
  notFoundHint: '(type help to see the commands)',
  // Fog's coaching (optional helper)
  coachStart: hasPhoto => hasPhoto
    ? 'I’ll walk you through it. The buttons under the terminal fill in commands: tap “cd Downloads”, then “Run” or Enter.'
    : 'I’ll walk you through it. First open the browser, go to “Nameless Square” on the bookmarks bar, and tap “Download original” on the leak post’s attachment. Then come back to the terminal.',
  coachDownloaded: 'Downloaded. Back in the terminal, tap “cd Downloads” and run it.',
  coachInDownloads: hasPhoto => hasPhoto ? 'Good, you’re in Downloads. Tap the “exiftool PXL_…” one and run it.' : 'You’re in Downloads, but there’s no photo yet. Download the attachment from the forum first.',
  coachAfterExif: 'That’s the data hidden in the photo, one field per line. Take your time: which lines did Night Heron never expect to leave behind?',
  // board
  boardSuspects: left => `Suspects · anonymity set: <span class="ev-count">${left}</span> left`,
  markHot: 'Suspicious',
  markOut: 'Rule out',
  notePlaceholder: 'Why you suspect or rule them out',
  boardClues: (n, total) => `Clues recorded · <span class="ev-count">${n}/${total}</span>`,
  noClues: 'Nothing yet. Reading the photo’s metadata or zooming into its details records clues here automatically.',
  boardPins: n => `Pinned · <span class="ev-count">${n}</span>`,
  noPins: 'Tap “📌 Pin” next to web pages, Slack logs and tables to save them here.',
  unpin: 'Unpin',
  // report
  reportTitle: 'Case report',
  reportNote: 'Your report to Night Heron. Back every answer with evidence; if you name the wrong person, Night Heron will tell you.',
  q1: '1. What did the photo’s metadata give away? (choose all that apply)',
  q2: '2. What did the picture itself give away? (choose all that apply)',
  q3: '3. What did the post’s writing give away?',
  q4: '4. Who is Night Heron?',
  chooseSuspect: 'Choose a suspect',
  chooseOne: '— Choose one —',
  submit: 'Submit report',
  correct: '✓ Correct',
  fb1: '✕ Look at the exiftool output again. What did Night Heron turn off, and what didn’t they?',
  fb2: '✕ Zoom into the photo in the image viewer. Two things in the picture tie back to the real world.',
  fb3: '✕ Night Heron used a new account and avoided the company network. What else could give them away?',
  fbNone: '✕ Choose a suspect.',
  fbWrong: '✕ The evidence doesn’t fit this person.',
  fbRightFixRest: '✓ You named the right person. Fix the answers marked wrong above and submit again to close the case.',
  yeluWrong: 'I read your report… it isn’t them. But the company’s investigators could make the same mistake and blame an innocent colleague. Can you look again?',
  yeluSolved: '…You found me. Thank you for getting there before they did. I’ll do what you suggest.',
  ranks: [['Chief Onion Investigator', 'The company’s investigators are still on their coffee and you’ve closed the case.'], ['Senior Privacy Volunteer', 'Night Heron is safe.'], ['Trainee Investigator', 'At least you’ll strip the EXIF before you post next time.']],
  rankStats: (hints, wrong, mistakes) => `You used ${hints} hint${hints === 1 ? '' : 's'} and named the wrong person ${wrong} time${wrong === 1 ? '' : 's'}${mistakes ? ', and uploaded the original photo to an online tool' : ''}. `,
  rankPerfect: 'No hints, right first time. ',
  rankLabel: 'Rank: ',
  replay: 'Play again',
  solvedTitle: 'Case report — closed',
};
