/* Interface text for the interactive page, 中文. The build inlines one ui.<lang>.js as UI.
   Keys used in the page's HTML as {{key}} must be plain strings; the rest may be functions. */
const UI = {
  lang: 'zh-Hant-TW',
  caseTitle: '夜鷺事件',
  pdfName: '夜鷺事件.pdf',
  description: '隱私推理遊戲：從一張照片的中繼資料、背景與文字習慣，找出不小心暴露身分的吹哨者。',
  // no-JS and fallback notices (HTML)
  nojsTitle: '這個版本需要 JavaScript',
  nojsBody: '《夜鷺事件》互動版模擬一台調查員的電腦，需要 JavaScript 才能運作。你的瀏覽器目前停用了 JavaScript，例如 Tor Browser 的「最安全」安全等級。',
  nojsStatic: '不需要 JavaScript 的靜態版，一樣可以完整破案：',
  nojsGo: '前往靜態版',
  nojsPdf: '想離線或印出來玩，也可以<a href="night-heron.pdf" download="夜鷺事件.pdf">下載 PDF 版</a>（解答在最後幾頁）。',
  fallbackTitle: '互動版無法在這個瀏覽器上運作',
  fallbackLoad: '載入時發生錯誤。',
  fallbackStay: '繼續嘗試互動版',
  fallbackFeatures: '你的瀏覽器缺少互動版需要的功能。',
  // desktop
  stickyTitle: '今晚的任務',
  sticky1: '讀夜鷺的訊息',
  sticky2: '找出照片洩漏了什麼',
  sticky3: '把 6 人縮到 1 人',
  sticky4: '交出結案報告',
  station: '霧港工作站',
  appChat: '加密通訊',
  lobbyHref: '../',
  langHref: '../en/night-heron/',
  otherLang: 'en',
  menuLobby: '委託板',
  menuLobbyTitle: '回到所有案件',
  menuPdf: 'PDF 版',
  menuPdfTitle: '可列印的 PDF 版，解答在最後幾頁',
  menuLang: 'English',
  menuLangTitle: '英文版',
  menuReset: '重新開始',
  menuResetConfirm: '再按一次確認重來',
  clockDate: '9月16日 週三 ',
  moreLabel: '更多選項',
  dockLabel: '應用程式',
  apps: { chat: '加密通訊', browser: '瀏覽器', files: '檔案', viewer: '看圖', doc: '文件', terminal: '終端機', board: '調查板', report: '結案報告' },
  locked: '（尚未解鎖）',
  close: '關閉',
  minimize: '縮小',
  lockedToast: ['還不能開始調查', '先和夜鷺聊完、收下資料再說。'],
  // toasts and pins
  clueToast: '新線索已記錄到調查板',
  pin: '📌 釘選',
  pinned: '已釘選',
  pinnedToast: '已釘選到調查板',
  downloadToast: fn => ['下載完成', fn + ' → 下載項目'],
  // chat
  yelu: '夜鷺',
  awu: '阿霧 · 互助站',
  yeluAvatar: '鷺',
  awuAvatar: '霧',
  e2e: '端對端加密',
  typing: '正在輸入…',
  awuSub: '提示與支援',
  headYelu: '夜鷺 · 安全碼已驗證',
  headYeluTyping: '夜鷺正在輸入…',
  headAwu: '阿霧 · 互助站內部頻道',
  chatOpening: '— 安全碼已驗證 · 訊息 24 小時後自動銷毀 —',
  zipName: '夜鷺匯出.zip',
  zipMeta: '48 KB · 加密傳送',
  zipSent: '傳送了一個檔案：夜鷺匯出.zip',
  zipReceived: '已接收 夜鷺匯出.zip · 解壓縮到 ~/夜鷺匯出',
  received: '已接收 ✓',
  accept: '接收',
  typingAria: '夜鷺正在輸入',
  caseOpen: '— 委託成立 · 調查開始 —',
  startToast: ['調查開始', '所有 App 已解鎖。從瀏覽器、檔案或終端機開始吧。'],
  awuHello: '我是阿霧，今晚值班。夜鷺的案子你接了吧？',
  hintButton: (n, total) => `給我提示（已用 ${n}/${total}）`,
  helperButton: on => `${on ? '關閉' : '開啟'}終端機新手輔助`,
  hintAsk: '給我一個提示。',
  hintLine: (n, total, h) => `提示 ${n}/${total}：${h}`,
  hintsDone: '提示都給完了。剩下的就交給你的直覺……不對，交給證據。',
  openBrowser: '打開瀏覽器',
  openFiles: '打開夜鷺匯出的資料',
  fastForward: '快轉 ▸▸',
  chooseReply: '選擇你的回覆',
  acceptHint: '按檔案上的「接收」收下資料',
  skipIntro: '跳過開場',
  // browser
  back: '上一頁',
  forward: '下一頁',
  reload: '重新整理',
  address: '網址',
  previewAttachment: '預覽附圖',
  downloaded: '已下載 ✓',
  downloadOriginal: '下載原始檔',
  saveImage: '儲存圖片',
  uploaded: '已上傳',
  upload: '上傳',
  trap: ['等一下，你剛把夜鷺的原始照片上傳到一個不明網站？', '那個網站現在也有這張照片了，還記下了你的 IP 和上傳時間。要是公司的調查員也找上它……\n下次請用自己電腦上的工具查，例如終端機的 exiftool。這次結案評等會降一級。'],
  // files and documents
  sideHome: '家目錄',
  sideDownloads: '下載項目',
  sideSlack: 'Slack 紀錄',
  upOne: '上一層',
  checkInTerminal: '終端機檢查',
  downloadsEmpty: '下載項目是空的。<br>從瀏覽器下載的檔案會出現在這裡。',
  folderEmpty: '這個資料夾是空的。',
  filesTitle: dir => '檔案 — ' + dir,
  verbatim: '原文照錄，未修改任何標點與空格。',
  colon: '：',
  // viewer
  viewerEmpty: '還沒有開啟任何圖片。<br>在「檔案」的下載項目，或論壇附件上點一下就能打開。',
  viewerTitle: fn => '看圖 — ' + fn,
  zoomOut: '縮小',
  zoomIn: '放大',
  fit: '符合視窗',
  fileInfo: '檔案資訊',
  infoFile: '檔案',
  infoName: '檔名',
  infoSize: '尺寸',
  infoBytes: '檔案大小',
  infoWhere: '存放位置',
  infoPreview: '（網頁預覽，尚未下載）',
  cameraInfo: '相機資訊',
  noCamera: '這個檔案沒有相機資訊。',
  tipDownloaded: '這裡只列出常見欄位，有些欄位不會顯示。用 EXIF 工具可以讀到更完整的中繼資料。',
  tipNotDownloaded: '要查看相機資訊，請先把原始檔<b>下載</b>下來。',
  saveFile: '把這個檔案存到你的電腦',
  realJpeg: '它是真的 JPEG，也可以用你自己的工具檢查。',
  controls: phone => '操作：' + (phone ? '兩指縮放，拖曳移動，點兩下放大。' : '滾輪或 ＋／－ 縮放，拖曳移動，雙擊放大。'),
  // terminal
  termInput: '終端機指令',
  termWelcome: '輸入 <span class="k">help</span> 查看可用指令。',
  tbCommand: '指令',
  tbPattern: '要找的字',
  tbPatternAria: 'grep 要找的字',
  tbAdd: '加入',
  tbFolders: '資料夾',
  tbFiles: '檔案',
  tbBack: '刪掉最後一段',
  tbHistory: '↑ 上一個',
  tbKeyboard: '⌨ 自己打字',
  run: '執行 ↵',
  suggested: '建議指令（點一下會填入）',
  useBuilder: '改用指令積木',
  helperToggle: on => `新手輔助：${on ? '開' : '關'}`,
  help: `可用指令：
  <span class="k">ls</span> [資料夾]          列出檔案
  <span class="k">cd</span> &lt;資料夾&gt;          切換資料夾（cd .. 回上一層）
  <span class="k">pwd</span>                  顯示目前位置
  <span class="k">cat</span> &lt;檔案&gt;           顯示文字檔內容
  <span class="k">exiftool</span> &lt;檔案&gt;      讀取檔案的中繼資料
  <span class="k">grep</span> [-i] &lt;字&gt; &lt;檔案...&gt;  在檔案中搜尋文字，支援 *.log
  <span class="k">file</span> &lt;檔案&gt;          判斷檔案類型
  <span class="k">open</span> &lt;檔案&gt;          用圖形介面開啟
  <span class="k">clear</span>                清除畫面
<span class="d">小技巧：按 Tab 自動補完檔名，↑ ↓ 叫出之前的指令。</span>`,
  noSuchFileOrDir: '沒有此檔案或目錄',
  empty: '（空的）',
  noSuchDir: '沒有此目錄',
  isDir: '是一個目錄',
  noSuchFile: '沒有此檔案',
  cannotOpen: '無法開啟',
  binary: '（二進位檔案，看不懂的亂碼……試試 exiftool 或 open）',
  usage: '用法',
  usageCat: '用法：cat &lt;檔案&gt;',
  usageOpen: '用法：open &lt;檔案&gt;',
  usageExif: '用法：exiftool &lt;檔案&gt;</span>\n<span class="d">例如：exiftool PXL_20260914_144712345.jpg',
  usageGrep: '用法：grep [-i] &lt;要找的字&gt; &lt;檔案...&gt;</span>\n<span class="d">例如：grep Pixel slack/*.log',
  noMatch: '（沒有符合的內容）',
  disabledCmd: '這台工作站停用了這個指令。專心查案吧。',
  notFoundHint: '（輸入 help 查看可用指令）',
  // 阿霧's coaching (optional helper)
  coachStart: hasPhoto => hasPhoto
    ? '我帶你。終端機下方的按鈕會幫你填好指令：先點「cd Downloads」，再按「執行」或 Enter。'
    : '我帶你。先打開瀏覽器，到書籤列的「無名廣場」，在爆料文的附件按「下載原始檔」。下載好再回來終端機。',
  coachDownloaded: '下載好了。回到終端機，點「cd Downloads」再按執行。',
  coachInDownloads: hasPhoto => hasPhoto ? '很好，你現在在「下載項目」裡。點「exiftool PXL_…」那一顆，再按執行。' : '你已經在下載項目了，不過裡面還沒有照片。先去論壇把附件下載下來。',
  coachAfterExif: '這些就是藏在照片裡的資料，每一行是一個欄位。慢慢看：有哪幾行，是夜鷺沒想到會留下來的？',
  // board
  boardSuspects: left => `嫌疑人 · 匿名集合剩 <span class="ev-count">${left}</span> 人`,
  markHot: '可疑',
  markOut: '排除',
  notePlaceholder: '排除或懷疑的理由',
  boardClues: (n, total) => `自動記錄的線索 · <span class="ev-count">${n}/${total}</span>`,
  noClues: '還沒有發現。讀取照片的中繼資料、放大照片細節，都會自動記錄在這裡。',
  boardPins: n => `釘選的資料 · <span class="ev-count">${n}</span>`,
  noPins: '在網頁、Slack 紀錄、表格旁按「📌 釘選」，就會存到這裡。',
  unpin: '取消釘選',
  // report
  reportTitle: '結案報告',
  reportNote: '交給夜鷺的報告。每一題都要有證據支撐；指認錯人，夜鷺會告訴你。',
  q1: '1. 照片的中繼資料洩漏了哪些資訊？（複選）',
  q2: '2. 照片畫面本身洩漏了什麼？（複選）',
  q3: '3. 爆料文的文字洩漏了什麼？',
  q4: '4. 夜鷺是誰？',
  chooseSuspect: '選擇嫌疑人',
  chooseOne: '— 選擇一位 —',
  submit: '提交報告',
  correct: '✓ 正確',
  fb1: '✕ 再看一次 exiftool 的輸出。夜鷺關掉了什麼？沒關掉什麼？',
  fb2: '✕ 用看圖 App 放大照片，畫面裡有兩樣東西能對應到現實。',
  fb3: '✕ 夜鷺用了新帳號、沒用公司網路。剩下能出賣人的是什麼？',
  fbNone: '✕ 請選擇一位嫌疑人。',
  fbWrong: '✕ 證據對不上這個人。',
  fbRightFixRest: '✓ 你指認的人沒錯。把上面錯的題目修正後再交一次，才能結案。',
  yeluWrong: '我讀了你的報告……不是那個人。但公司的調查員也可能這樣誤判，冤枉一個無辜的同事。可以再查一次嗎？',
  yeluSolved: '……你找到我了。謝謝你比他們早一步。我會照你的建議處理。',
  ranks: [['洋蔥首席調查員', '公司的調查員還在喝咖啡，你已經破案了。'], ['資深隱私志工', '夜鷺得救了。'], ['見習調查員', '至少你知道下次發文前要先清 EXIF 了。']],
  rankStats: (hints, wrong, mistakes) => `用了 ${hints} 個提示、誤判 ${wrong} 次${mistakes ? '，還把原始照片上傳到線上工具' : ''}。`,
  rankPerfect: '沒看任何提示，一次就指認正確。',
  rankLabel: '評等：',
  replay: '重新開始一局',
  solvedTitle: '結案報告 — 已結案',
};
